name: Generate contributors

on:
  pull_request:
    branches: [ main ]
    types:
      - closed

jobs:
  generate:
    
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        node-version: [12.x]
        email: ['1581446178@qq.com']
        name: ['ChelesteWang']
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: npx git-contributor

    - name: config git
      run: git config --global user.email ${{ matrix.email }} &&git config --global user.name ${{ matrix.name }}

    - name: checkout work branch

      run: git checkout -b contributor

    - name: check for changes
      run: git status
      
    - name: stage changed files
      run: git add .

    - name: commit changed files
      run: git commit -m "update by github actions"
      
    - name: pull code
      run: git pull
      
    - name: push code
      run: git push origin contributor
